### ISSUE TITLE
Illegal memory access after creating SRU modules on CPU and GPU in the same script

### ISSUE THREAD

**Issue by felixgwu** [OpenNMT/OpenNMT#541]
I got the following error when running SRU modules on both CPU and GPU.
This also happens when I train a model on a GPU, save it, and load it again to inference on CPUs.

```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCTensorCopy.c line=21 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "test_onmt_sru.py", line 15, in <module>
    sru = onmt.modules.SRU(32, 16).cuda()
  File "/home/felix/.conda/envs/pytorch-0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/felix/.conda/envs/pytorch-0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/felix/.conda/envs/pytorch-0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/felix/.conda/envs/pytorch-0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/home/felix/.conda/envs/pytorch-0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/felix/.conda/envs/pytorch-0.3.1/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCTensorCopy.c:21
```

I am using PyTorch 0.3.1 with CUDA 9.1 and CuDNN 7.0.
Also, I'm using cupy==4.0.0 and pynvrtc==8.0.
Here is the script to reproduce it. 

```python
import torch
from torch.autograd import Variable
import onmt

print('cpu')
sru = onmt.modules.SRU(32, 16).cpu()
inputs = Variable(torch.rand(30, 4, 32))
o, f = sru(inputs)


print('gpu')
sru = onmt.modules.SRU(32, 16).cuda()
inputs = Variable(torch.rand(30, 4, 32)).cuda()
o, f = sru(inputs)


print('cpu')
sru = onmt.modules.SRU(32, 16).cpu()
inputs = inputs.cpu()
o, f = sru(inputs)
```

**Comment by guillaumekln** [comment]
You should open this issue in [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py).
