### ISSUE TITLE
ModuleNotFoundError: No module named 'onmt.inputters'

### ISSUE THREAD

**Issue by Roweida-Mohammed** [OpenNMT/OpenNMT#579]
hello :)
When I use the python train_mm.py  it gave me this error

Traceback (most recent call last):
  File "train_mm.py", line 448, in <module>
    main()
  File "train_mm.py", line 423, in main
    first_dataset = next(lazily_load_dataset("train"))
  File "train_mm.py", line 314, in lazily_load_dataset
    yield lazy_dataset_loader(pt, corpus_type)
  File "train_mm.py", line 305, in lazy_dataset_loader
    dataset = torch.load(pt_file)
  File "C:\Users\user\Anaconda3\envs\thesis1\lib\site-packages\torch\serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\user\Anaconda3\envs\thesis1\lib\site-packages\torch\serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'onmt.inputters'

**Comment by guillaumekln** [comment]
https://github.com/OpenNMT/OpenNMT-py/issues/1802
